name: update test-weather-alert.py

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: execute py script # run test-weather-alert.py
        env:
          DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
          run: python test-weather-alert.py
