name: update test-weather-alert.py
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9' # install the python version needed

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: execute py script # run test-weather-alert.py
        env:
          DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: python test-weather-alert.py
