name: update test-weather-alert.py

on: [push]

jobs:
  update_maps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Update Canada weather alerts
        env:
            DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: |
          python3 test-weather-alerts.py
