name: update test-weather-alert.py

on: [push]

jobs:
  update_maps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.9"
          cache: 'pip'  # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Update Canada weather alerts
        env:
            DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: |
          python test-weather-alerts.py
