name: update test-weather-alert.py

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3


      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        env:
          DW_AUTH_TOKEN: ${{ secrets.DW_AUTH_TOKEN }}
        run: python3 test-weather-alert.py
